---
#
# Tasks to setup hypershift and install hosted clusters
#
# Flow:
# * clone e2e-benchmarking
# * run hypershift cleanup


- name: clone e2e-benchmarking
  ansible.builtin.git:
    repo: 'https://github.com/cloud-bulldozer/e2e-benchmarking.git'
    dest: /tmp/e2e-benchmarking
    version: master

- name: run hypershift cleanup
  ansible.builtin.shell: ./run.sh clean | tee "{{ playbook_dir }}/cleanup.log"
  args:
    chdir: /tmp/e2e-benchmarking/workloads/hyper-scale
