---
#
# Install OSD clusters using OCM
#

- name: Perform OSD cluster install
  hosts: orchestration
  become: true
  gather_facts: true
  remote_user: "{{orchestration_user}}"
  vars_files:
    - vars/install-common-vars.yml
  pre_tasks:

    - name: Include platform variables
      include_vars:
        file: "vars/install-on-{{ platform }}.yml"

  roles:
    - role: openshift-cleanup
      when: openshift_cleanup|bool
    - role: openshift-install
      when: openshift_install|bool
    - role: thanos
      when: thanos_enable|bool
