---
#
# Delete OSD clusters using OCM
#

- name: Perform OSD and HyperShift cluster uninstall
  hosts: orchestration
  become: true
  gather_facts: true
  remote_user: "{{orchestration_user}}"
  vars_files:
    - vars/install-common-vars.yml

  roles:
    - role: hypershift-cleanup
      when: hypershift_cleanup|bool 
    - role: openshift-cleanup
      when: openshift_cleanup|bool
