---
#
# Tasks to setup hypershift and install hosted clusters
#
# Flow:
# * Install dependencies
# * clone e2e-benchmarking
# * run hypershift installer


- name: Install dependencies
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - make
      - jq

- name: Install awscli
  pip:
    name: awscli

- name: clone e2e-benchmarking
  ansible.builtin.git:
    repo: 'https://github.com/cloud-bulldozer/e2e-benchmarking.git'
    dest: /tmp/e2e-benchmarking
    version: master

- name: run installer 
  ansible.builtin.shell: ./run.sh build | tee "{{ playbook_dir }}/install.log"
  args:
    chdir: /tmp/e2e-benchmarking/workloads/hyper-scale
