---
#
# Tasks to setup OCM and install OSD
#
# Flow:
# * Install OCM client
# * OCM login
# * Define the cluster config
# * Install cluster
#

- name: Install OCM client and dependencies
  yum:
    name: "{{ packages }}"
    enablerepo: ocm/tools
    state: present
  vars:
    packages:
      - ocm-cli
      - jq

- name: OCM login to connect to console.redhat.com
  shell: ocm login --url={{ ocm_url }} --token={{ ocm_api_token }}

- name: Setup cluster configuration
  template:
     src:  install-config-{{platform}}.json.j2 
     dest: "{{ playbook_dir }}/cluster-config-{{ platform }}"

- name: Create cluster
  shell: ocm post /api/clusters_mgmt/v1/clusters --body={{ playbook_dir }}/cluster-config-{{ platform }}
  register: cluster_status

- name: Get cluster id
  shell: ocm list clusters --no-headers --columns id {{ cluster_name }} 
  register: cluster_id

- name: Get cluster status and wait till it's installed with a 60 minutes timeout
  shell: ocm list clusters --no-headers --columns state {{ cluster_name }}
  register: cluster_status
  until: cluster_status.stdout | trim == "ready" 
  retries: 36
  delay: 100

- name: Capture kubeconfig
  shell: ocm get /api/clusters_mgmt/v1/clusters/{{ cluster_id.stdout }}/credentials | jq -r .kubeconfig
  register: kubeconfig

- name: Copy kubeconfig to default location
  shell: cat {{ kubeconfig.stdout }} > {{ kubeconfig_path }}
